#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI-5.30

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 6 * * 5
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: 空间清理（Space cleanup）
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          
          df -h

      - name: 自定义插件主题。
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          # git clone https://github.com/rosywrt/luci-theme-rosy.git
          # git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          # git clone https://github.com/xkstudio/luci-app-pptp-server.git
          git clone https://github.com/destan19/OpenAppFilter.git
          git clone https://github.com/vernesong/OpenClash.git
          git clone https://github.com/fw876/helloworld.git
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          git clone https://github.com/tty228/luci-app-serverchan.git
          git clone https://github.com/jerrykuku/luci-app-jd-dailybonus.git
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
          # git clone https://github.com/xiaorouji/openwrt-passwall.git
          # git clone https://github.com/kenzok8/openwrt-packages.git
          git clone https://github.com/liuran001/openwrt-packages.git
          # git clone https://github.com/xiaozhuai/luci-app-filebrowser.git
          git clone https://github.com/apollo-ng/luci-theme-darkmatter.git

      - name: 更新源（Update feeds）
        run: |
          sed -i 's/192.168.1.1/10.6.9.2/g' package/base-files/files/bin/config_generate
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 生成配置文件（Generate configuration file）
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_TARGET_KERNEL_PARTSIZE=64
          CONFIG_TARGET_ROOTFS_PARTSIZE=960
          
          # 固件压缩:
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          CONFIG_KERNEL_BUILD_DOMAIN="Azure"
          
          # 编译UEFI固件:
          CONFIG_EFI_IMAGES=y
          
          # IPv6支持:
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          
          # 多文件系统支持:
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          
          # USB3.0支持:
          # CONFIG_PACKAGE_kmod-usb-ohci=y
          # CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          # CONFIG_PACKAGE_kmod-usb2=y
          # CONFIG_PACKAGE_kmod-usb2-pci=y
          # CONFIG_PACKAGE_kmod-usb3=y
          
          # 增加Wifi驱动:
          CONFIG_PACKAGE_iwlwifi-firmware-iwl8260c=y
          CONFIG_PACKAGE_kmod-iwlwifi=y
          CONFIG_B43LEGACY_FW_SQUASH=y
          CONFIG_B43LEGACY_FW_SQUASH_COREREVS="1,2,3,4"
          CONFIG_B43_FW_5_100_138=y
          CONFIG_B43_FW_SQUASH=y
          CONFIG_B43_FW_SQUASH_COREREVS="5,6,7,8,9,10,11,13,15,16,28,29,30"
          CONFIG_B43_FW_SQUASH_PHYTYPES="G,N,LP,HT"
          CONFIG_BRCMFMAC_PCIE=y
          CONFIG_BRCMFMAC_USB=y
          CONFIG_BRCMSMAC_USE_FW_FROM_WL=y
          CONFIG_DRIVER_11AX_SUPPORT=y
          CONFIG_DRIVER_WEXT_SUPPORT=y
          CONFIG_PACKAGE_B43_BUSES_BCMA_AND_SSB=y
          CONFIG_PACKAGE_B43_PHY_G=y
          CONFIG_PACKAGE_B43_PHY_HT=y
          CONFIG_PACKAGE_B43_PHY_LP=y
          CONFIG_PACKAGE_B43_PHY_N=y
          CONFIG_PACKAGE_B43_USE_BCMA=y
          CONFIG_PACKAGE_B43_USE_SSB=y
          CONFIG_PACKAGE_b43legacy-firmware=y
          CONFIG_PACKAGE_brcmfmac-firmware-4366b1-pcie=y
          CONFIG_PACKAGE_brcmfmac-firmware-4366c0-pcie=y
          CONFIG_PACKAGE_brcmfmac-firmware-usb=y
          CONFIG_PACKAGE_carl9170-firmware=y
          CONFIG_PACKAGE_cypress-firmware-4356-pcie=y
          CONFIG_PACKAGE_cypress-firmware-43570-pcie=y
          CONFIG_PACKAGE_cypress-firmware-4373-usb=y
          CONFIG_PACKAGE_cypress-firmware-54591-pcie=y
          CONFIG_PACKAGE_iwl3945-firmware=y
          CONFIG_PACKAGE_iwl4965-firmware=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl100=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl1000=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl105=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl135=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl2000=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl2030=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl3160=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl3168=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl5000=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl5150=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2a=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl6000g2b=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl6050=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl7260=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl7265=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl7265d=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl8265=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl9000=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl9260=y
          CONFIG_PACKAGE_kmod-adm8211=y
          CONFIG_PACKAGE_kmod-ath6kl=y
          CONFIG_PACKAGE_kmod-ath6kl-usb=y
          CONFIG_PACKAGE_kmod-b43=y
          CONFIG_PACKAGE_kmod-b43legacy=y
          CONFIG_PACKAGE_kmod-bcma=y
          CONFIG_PACKAGE_kmod-brcmfmac=y
          CONFIG_PACKAGE_kmod-brcmsmac=y
          CONFIG_PACKAGE_kmod-brcmutil=y
          CONFIG_PACKAGE_kmod-carl9170=y
          CONFIG_PACKAGE_kmod-hermes=y
          CONFIG_PACKAGE_kmod-hermes-pci=y
          CONFIG_PACKAGE_kmod-ipw2100=y
          CONFIG_PACKAGE_kmod-ipw2200=y
          CONFIG_PACKAGE_kmod-iwl-legacy=y
          CONFIG_PACKAGE_kmod-iwl3945=y
          CONFIG_PACKAGE_kmod-iwl4965=y
          CONFIG_PACKAGE_kmod-lib-cordic=y
          CONFIG_PACKAGE_kmod-lib-crc8=y
          CONFIG_PACKAGE_kmod-lib80211=y
          CONFIG_PACKAGE_kmod-libertas-usb=y
          CONFIG_PACKAGE_kmod-libipw=y
          CONFIG_PACKAGE_kmod-mt76=y
          CONFIG_PACKAGE_kmod-mt76-core=y
          CONFIG_PACKAGE_kmod-mt76-usb=y
          CONFIG_PACKAGE_kmod-mt7601u=y
          CONFIG_PACKAGE_kmod-mt7603=y
          CONFIG_PACKAGE_kmod-mt7615-common=y
          CONFIG_PACKAGE_kmod-mt7615-firmware=y
          CONFIG_PACKAGE_kmod-mt7615e=y
          CONFIG_PACKAGE_kmod-mt7663-firmware-ap=y
          CONFIG_PACKAGE_kmod-mt7663-usb-sdio=y
          CONFIG_PACKAGE_kmod-mt7663u=y
          CONFIG_PACKAGE_kmod-mt76x0-common=y
          CONFIG_PACKAGE_kmod-mt76x02-common=y
          CONFIG_PACKAGE_kmod-mt76x02-usb=y
          CONFIG_PACKAGE_kmod-mt76x0e=y
          CONFIG_PACKAGE_kmod-mt76x0u=y
          CONFIG_PACKAGE_kmod-mt76x2=y
          CONFIG_PACKAGE_kmod-mt76x2-common=y
          CONFIG_PACKAGE_kmod-mt76x2u=y
          CONFIG_PACKAGE_kmod-mt7915e=y
          CONFIG_PACKAGE_kmod-mwifiex-pcie=y
          CONFIG_PACKAGE_kmod-mwl8k=y
          CONFIG_PACKAGE_kmod-net-prism54=y
          CONFIG_PACKAGE_kmod-net-rtl8192su=y
          CONFIG_PACKAGE_kmod-owl-loader=y
          CONFIG_PACKAGE_kmod-p54-common=y
          CONFIG_PACKAGE_kmod-p54-pci=y
          CONFIG_PACKAGE_kmod-p54-usb=y
          CONFIG_PACKAGE_kmod-rsi91x=y
          CONFIG_PACKAGE_kmod-rsi91x-usb=y
          CONFIG_PACKAGE_kmod-rt2400-pci=y
          CONFIG_PACKAGE_kmod-rt2500-pci=y
          CONFIG_PACKAGE_kmod-rt2500-usb=y
          CONFIG_PACKAGE_kmod-rt2800-mmio=y
          CONFIG_PACKAGE_kmod-rt2800-pci=y
          CONFIG_PACKAGE_kmod-rt2x00-mmio=y
          CONFIG_PACKAGE_kmod-rt2x00-pci=y
          CONFIG_PACKAGE_kmod-rt61-pci=y
          CONFIG_PACKAGE_kmod-rt73-usb=y
          CONFIG_PACKAGE_kmod-rtl8180=y
          CONFIG_PACKAGE_kmod-rtl8187=y
          CONFIG_PACKAGE_kmod-rtl8188eu=y
          CONFIG_PACKAGE_kmod-rtl8192c-common=y
          CONFIG_PACKAGE_kmod-rtl8192ce=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-rtl8192du=y
          CONFIG_PACKAGE_kmod-rtl8192de=y
          CONFIG_PACKAGE_kmod-rtl8192se=y
          CONFIG_PACKAGE_kmod-rtl8812au-ac=y
          CONFIG_PACKAGE_kmod-rtl8821cu=y
          CONFIG_PACKAGE_kmod-rtl8821ae=y
          CONFIG_PACKAGE_kmod-rtl88x2bu=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          CONFIG_PACKAGE_kmod-rtlwifi=y
          CONFIG_PACKAGE_kmod-rtlwifi-btcoexist=y
          CONFIG_PACKAGE_kmod-rtlwifi-pci=y
          CONFIG_PACKAGE_kmod-rtlwifi-usb=y
          CONFIG_PACKAGE_kmod-rtw88=y
          CONFIG_PACKAGE_kmod-ssb=y
          CONFIG_PACKAGE_kmod-wl12xx=y
          CONFIG_PACKAGE_kmod-wl18xx=y
          CONFIG_PACKAGE_kmod-wlcore=y
          CONFIG_PACKAGE_kmod-zd1211rw=y
          CONFIG_PACKAGE_libertas-usb-firmware=y
          CONFIG_PACKAGE_mt7601u-firmware=y
          CONFIG_PACKAGE_mwifiex-pcie-firmware=y
          CONFIG_PACKAGE_mwl8k-firmware=y
          CONFIG_PACKAGE_p54-pci-firmware=y
          CONFIG_PACKAGE_p54-usb-firmware=y
          CONFIG_PACKAGE_prism54-firmware=y
          CONFIG_PACKAGE_rs9113-firmware=y
          CONFIG_PACKAGE_rt2800-pci-firmware=y
          CONFIG_PACKAGE_rt61-pci-firmware=y
          CONFIG_PACKAGE_rt73-usb-firmware=y
          CONFIG_PACKAGE_rtl8188eu-firmware=y
          CONFIG_PACKAGE_rtl8192ce-firmware=y
          CONFIG_PACKAGE_rtl8192cu-firmware=y
          CONFIG_PACKAGE_rtl8192de-firmware=y
          CONFIG_PACKAGE_rtl8192eu-firmware=y
          CONFIG_PACKAGE_rtl8192se-firmware=y
          CONFIG_PACKAGE_rtl8192su-firmware=y
          CONFIG_PACKAGE_rtl8723au-firmware=y
          CONFIG_PACKAGE_rtl8723bu-firmware=y
          CONFIG_PACKAGE_rtl8821ae-firmware=y
          CONFIG_PACKAGE_rtl8822be-firmware=y
          CONFIG_PACKAGE_rtl8822ce-firmware=y
          CONFIG_PACKAGE_wl12xx-firmware=y
          CONFIG_PACKAGE_wl18xx-firmware=y
          
          # 常用LuCI插件选择:
          # CONFIG_PACKAGE_luci-app-oaf=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-jd-dailybonus=y
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-app-dnsfilter=y
          CONFIG_PACKAGE_luci-app-advancedsetting=y
          # CONFIG_PACKAGE_luci-app-aliddns=y
          # CONFIG_PACKAGE_luci-app-eqos=y
          # CONFIG_PACKAGE_luci-app-gost=y
          # CONFIG_PACKAGE_luci-app-smartdns=y
          # CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-accesscontrol=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-advanced-reboot=y
          CONFIG_PACKAGE_luci-app-ahcp=y
          CONFIG_PACKAGE_luci-app-arpbind=y
          CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          CONFIG_PACKAGE_luci-app-cifsd=y
          CONFIG_PACKAGE_luci-app-clamav=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-familycloud=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          CONFIG_PACKAGE_luci-app-ipsec-vpnd=y
          CONFIG_PACKAGE_luci-app-kodexplorer=y
          CONFIG_PACKAGE_luci-app-minidlna=y
          CONFIG_PACKAGE_luci-app-mjpg-streamer=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-nft-qos=y
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-noddos=y
          CONFIG_PACKAGE_luci-app-ntpc=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_luci-app-rp-pppoe-server=y
          CONFIG_PACKAGE_luci-app-pppoe-relay=y
          CONFIG_PACKAGE_luci-app-pptp-server=y
          CONFIG_PACKAGE_luci-app-p910nd=y
          CONFIG_PACKAGE_luci-app-polipo=y
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-radicale=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-shairplay=y
          CONFIG_PACKAGE_luci-app-simple-adblock=y
          CONFIG_PACKAGE_luci-app-splash=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_DNS2SOCKS=y
          CONFIG_PACKAGE_luci-app-ssrserver-python=y
          CONFIG_PACKAGE_luci-app-statistics=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-travelmate=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-udpxy=y
          CONFIG_PACKAGE_luci-app-uhttpd=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_UnblockNeteaseMusic_Go=y
          CONFIG_UnblockNeteaseMusic_NodeJS=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-verysync=y
          CONFIG_PACKAGE_luci-app-vpnbypass=y
          CONFIG_PACKAGE_luci-app-vsftpd=y
          # CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wifischedule=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-xlnetacc=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-nps=y
          CONFIG_PACKAGE_luci-app-oaf=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-jd-dailybonus=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-cifs-mount=y
          
          # LuCI主题:
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          CONFIG_PACKAGE_luci-theme-rosy=y
          CONFIG_PACKAGE_luci-theme-ifit=y
          CONFIG_PACKAGE_luci-theme-argon_new=y
          CONFIG_PACKAGE_luci-theme-darkmatter=y
          
          # 常用软件包:
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_vsftpd-alt=y
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
          CONFIG_PACKAGE_wget=y
          
          
          EOF
          
          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: 制作下载（Make download）
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: 编译固件（Compile firmware）
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: 准备神器（Prepare artifact）
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: 交付构建信息（Deliver buildinfo）
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: 交付包裹（Deliver package）
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: 提供固件（Deliver firmware）
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: 上载发布（Upload release asset）
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
